# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/facial-misrecognition-systems',
                'doc_host': 'https://Irad-Zehavi.github.io',
                'git_url': 'https://github.com/Irad-Zehavi/facial-misrecognition-systems',
                'lib_path': 'facial_misrecognition_systems'},
  'syms': { 'facial_misrecognition_systems.core': { 'facial_misrecognition_systems.core.foo': ( 'core.html#foo',
                                                                                                'facial_misrecognition_systems/core.py')}}}
